create table if not exists public.task_notification_log (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tareas_proyecto(id) on delete cascade,
  notification_type text not null,
  notification_date date not null,
  recipient_email text not null,
  provider text not null,
  status text not null check (status in ('sent', 'failed')),
  metadata jsonb not null default '{}'::jsonb,
  error_message text null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_task_notification_log_task_date
  on public.task_notification_log (task_id, notification_date);

create index if not exists idx_task_notification_log_status
  on public.task_notification_log (status, notification_date desc);

create unique index if not exists uq_task_notification_log_sent_once_per_day
  on public.task_notification_log (task_id, notification_type, notification_date, recipient_email)
  where status = 'sent';
